# Generated by Django 4.0.8 on 2024-02-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_user_organization'),
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_news_events', to='accounts.organization'),
        ),
    ]
