# Generated by Django 4.0.8 on 2024-03-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsandevents_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
