# Generated by Django 4.0.8 on 2024-08-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_email'),
        ('core', '0007_newsandevents_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_session', to='accounts.organization'),
        ),
    ]
