# Generated by Django 4.0.8 on 2024-08-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_email'),
        ('core', '0008_session_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization_session', to='accounts.organization'),
            preserve_default=False,
        ),
    ]
