# Generated by Django 4.0.8 on 2024-02-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_user_organization'),
        ('course', '0006_courseoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Programs', to='accounts.organization'),
        ),
    ]
