# Generated by Django 4.0.8 on 2024-02-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
        ('course', '0007_program_organization'),
    ]

    operations = [
    ]
