# Generated by Django 4.0.8 on 2024-02-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_organization'),
        ('course', '0010_program_section_alter_program_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('title', 'section', 'organization')},
        ),
    ]
