# Generated by Django 4.0.8 on 2024-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
        ('course', '0011_alter_program_unique_together'),
    ]

    operations = [
    ]
