# Generated by Django 4.0.8 on 2024-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_merge_20240311_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Bachlor', 'Bachlor Degree'), ('Master', 'Master Degree'), ('College', 'College Degree'), ('Schooling', 'Schooling Degree')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=200),
        ),
    ]
