# Generated by Django 4.0.8 on 2024-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_merge_20240208_1848'),
        ('course', '0016_alter_course_semester'),
    ]

    operations = [
    ]
