# Generated by Django 4.0.8 on 2024-07-26 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0026_merge_0020_merge_20240208_1848_0025_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_subscription', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('month', models.DateField()),
                ('payment_complete', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('invoice_code', models.CharField(blank=True, max_length=200, null=True)),
                ('organizationsubscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.organizationsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.subscription'),
        ),
        migrations.CreateModel(
            name='OrganizationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('month', models.DateField()),
                ('payment_complete', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('invoice_code', models.CharField(blank=True, max_length=200, null=True)),
                ('organizationsubscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.organizationsubscription')),
            ],
        ),
    ]
