# Generated by Django 4.0.8 on 2024-07-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_0020_merge_20240208_1848_0025_alter_user_email'),
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsubscription',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
