# Generated by Django 4.0.8 on 2024-07-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_organizationsubscription_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinvoice',
            old_name='month',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='studentinvoice',
            old_name='month',
            new_name='date',
        ),
    ]
