# Generated by Django 4.0.8 on 2024-07-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_rename_month_organizationinvoice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinvoice',
            old_name='organizationsubscription',
            new_name='organization_subscription',
        ),
        migrations.RenameField(
            model_name='studentinvoice',
            old_name='organizationsubscription',
            new_name='organization_subscription',
        ),
    ]
