# Generated by Django 4.0.8 on 2024-07-31 12:37

import billings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_rename_organizationsubscription_organizationinvoice_organization_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinvoice',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='organizationinvoice',
            old_name='total',
            new_name='amount_payable',
        ),
        migrations.RenameField(
            model_name='organizationinvoice',
            old_name='date',
            new_name='billing_period_date',
        ),
        migrations.RenameField(
            model_name='studentinvoice',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='studentinvoice',
            old_name='total',
            new_name='amount_payable',
        ),
        migrations.RenameField(
            model_name='studentinvoice',
            old_name='date',
            new_name='billing_period_date',
        ),
        migrations.AddField(
            model_name='organizationinvoice',
            name='next_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentinvoice',
            name='next_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationinvoice',
            name='invoice_code',
            field=models.CharField(blank=True, default=billings.models.generate_uuid, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentinvoice',
            name='invoice_code',
            field=models.CharField(blank=True, default=billings.models.generate_uuid, max_length=200, null=True),
        ),
    ]
