# Generated by Django 4.0.8 on 2024-03-10 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_figure_alter_quiz_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(blank=True, default=50, help_text="Percentage required to pass exam, if it's not graded enter 0.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
    ]
