# Generated by Django 4.0.8 on 2024-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quiz_pass_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type_of_quiz',
            field=models.TextField(choices=[('MCQ', 'MCQ'), ('Essay', 'Essay')], default='MCQ'),
            preserve_default=False,
        ),
    ]
