# Generated by Django 4.0.8 on 2024-03-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_type_of_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='descriptive_questions_files/')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('instructor_answer', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Descriptive Question',
                'verbose_name_plural': 'Descriptive Questions',
            },
        ),
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.descriptivequestion')),
            ],
            options={
                'verbose_name': 'Descriptive Answer',
                'verbose_name_plural': 'Descriptive Answers',
            },
        ),
    ]
