# Generated by Django 4.0.8 on 2024-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_descriptivequestion_descriptiveanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type_of_quiz',
            field=models.TextField(choices=[('MCQ', 'MCQ'), ('Descriptive', 'Descriptive')]),
        ),
    ]
