# Generated by Django 4.0.8 on 2024-02-05 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_department_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type_of_org', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], max_length=100)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('establishment_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/%Y/%m/%d/')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
    ]
