# Generated by Django 4.0.8 on 2024-02-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_organization_user_organization'),
        ('accounts', '0019_user_gender'),
    ]

    operations = [
    ]
