# Generated by Django 4.0.8 on 2024-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_gender'),
        ('accounts', '0020_alter_user_organization'),
    ]

    operations = [
    ]
