# Generated by Django 4.0.8 on 2024-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Bachlor', 'Bachlor Degree'), ('Master', 'Master Degree'), ('College', 'College Degree'), ('Schooling', 'Schooling Degree')], max_length=25, null=True),
        ),
    ]
