# Generated by Django 4.0.8 on 2024-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20240208_1848'),
        ('accounts', '0025_alter_user_email'),
    ]

    operations = [
    ]
